config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      delete :delete_image_attachment
    end
  end
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :delete_image_attachment]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image_attachment
    @item.images.find(params[:image_id]).purge
    redirect_to @item
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:sku, :product_name, :price, :category, :color, :size, :storage_count, images: [])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    title += ' | ' if title.present?
    title += 'Mydlo&Powidlo'
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/items/_form.html.slim
= bootstrap_form_with(model: item, local: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |form|
  - if item.errors.any?
    div.error_explanation
    h2 =pluralize(item.errors.count, "error")
    |prohibited this item from being saved
    ul
      - item.errors.full_messages.each do |message|
        li = message

  div.field
    = form.number_field :sku

  div.field
    = form.text_area :product_name

  div.field
    = form.text_field :price

  div.field
    = form.text_area :category

  div.field
    = form.text_field :color

  div.field
    = form.label :size
    = form.text_field :size

  div.field
    = form.number_field :storage_count

  div.field
    = form.file_field :images, multiple: true

  div.actions
    = form.submit

app/views/items/edit.html.slim
h1 Editing Item

= render 'form', item: @item

= link_to 'Show', @item
= link_to 'Back', items_path

app/views/items/index.html.slim
h1 Items
table
  thead
    tr
      th Sku
      th Product name
      th Price
      th Category
      th Color
      th Size
      th Storage count
      th colspan="3"

  tbody
    - @items.each do |item|
      tr
        td = item.sku
        td = item.product_name
        td = item.price
        td = item.category
        td = item.color
        td = item.size
        td = item.storage_count
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
br

= link_to 'New Item', new_item_path

app/views/items/new.html.slim
h1 New Item

= render 'form', item: @item

= link_to 'Back', items_path

app/views/items/show.html.slim
- if !notice.nil?
  p#notice = notice

p
  strong Sku:
  = @item.sku

p
  strong Product name:
  = @item.product_name

p
  strong Price:
  = @item.price

p
  strong Category:
  = @item.category

p
  strong Color:
  = @item.color

p
  strong Size:
  = @item.size

p
  strong Storage count:
  = @item.storage_count

- if @item.images.attached?
  p
    - @item.images.each do |image|
      div
        = image_tag image.variant(resize_to_fit: [200, 200])
        = link_to 'Remove photo', delete_image_attachment_item_url(@item, image_id: image.id),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }
    br

= link_to 'Edit', edit_item_path(@item)
|   |
= link_to 'Back', items_path

app/views/layouts/_messages.html.slim
/ - if !flash.empty?
/   div#flash_messages
/     = flash.each do |key, value|
- if notice
  p#notice.alert.alert-success = notice
- if alert
  p#alert.alert.alert-danger = alert

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"
  a class="navbar-brand" href="#" Fixed navbar
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  div.collapse.navbar-collapse#navbarCollapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        = link_to 'Home', root_path, class: 'nav-link'
      li class="nav-item"
        a class="nav-link" href="#" Link
      li.nav-item
        a.nav-link.disabled href="#" Disabled
    ul.navbar-nav
      li.nav-item.dropdown
        - if signed_in?
          a.nav-link.dropdown-toggle href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" = current_user.email
        - else
          a.nav-link.dropdown-toggle href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Login
        div.dropdown-menu.dropdown-menu-right aria-labelledby='navbarDropdownMenuLink'
          - if !signed_in?
            div.devise-bootstrap-form
              div.devise-bootstrap-form-row.p-2
                div.devise-bootstrap-form-col
                  = bootstrap_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
                    = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: 'email@example.com'
                    = f.password_field :password, autocomplete: "current-password", placeholder: 'Password'

                    - if devise_mapping.rememberable?
                      = f.form_group do
                      = f.check_box :remember_me

                    = f.form_group do
                    = f.submit "Log in", class: "btn btn-primary btn-block btn-lg"
                div.dropdown-divider
                div.text-center
                = render "devise/shared/links"
          - else
            = link_to 'Edit Profile', edit_user_registration_path
            = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title MyStore
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/navbar'
    = render 'layouts/messages'

    main
    == yield

app/views/main/index.html.slim
h1 Main#index
p Find me in app/views/main/index.html.slim
img alt='piesel' src=asset_pack_path('media/images/puppy-dog.jpg')
/ div
/   - if user_signed_in?
/     = current_user.email
/     = link_to 'Edit profile', edit_user_registration_path
/     = link_to 'Logout', destroy_user_session_path, method: :delete
/   - else
/     = link_to 'Sign up', new_user_registration_path
/     = link_to 'Log in', new_user_session_path